#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Seconda parte delle traduzioni: i messaggi di stato e i suggerimenti.

Sono le frasi che compaiono quando qualcosa non va, ed e' li' che una
traduzione approssimativa fa danno: chi legge deve capire cosa fare, non
indovinare. I segnaposto %1 %2 restano al loro posto.
"""

T2 = {
 "manca il server di accesso": {
  "en": "the sign-in server is missing", "de": "Der Anmeldeserver fehlt",
  "fr": "il manque le serveur de connexion", "es": "falta el servidor de acceso",
  "pt": "falta o servidor de acesso", "nl": "de aanmeldserver ontbreekt",
  "ca": "falta el servidor d'accés", "da": "loginserveren mangler",
  "hu": "hiányzik a bejelentkezési kiszolgáló", "ro": "lipsește serverul de autentificare",
  "lv": "trūkst pieteikšanās servera", "ru": "не указан сервер входа",
  "ja": "ログインサーバーが未設定です", "zh": "缺少登录服务器", "zh_TW": "缺少登入伺服器",
 },
 "servono email e password": {
  "en": "email and password are required", "de": "E-Mail und Passwort werden benötigt",
  "fr": "e-mail et mot de passe sont requis", "es": "hacen falta correo y contraseña",
  "pt": "são necessários email e palavra-passe", "nl": "e-mail en wachtwoord zijn nodig",
  "ca": "calen correu i contrasenya", "da": "e-mail og adgangskode kræves",
  "hu": "e-mail-cím és jelszó szükséges", "ro": "sunt necesare emailul și parola",
  "lv": "nepieciešams e-pasts un parole", "ru": "нужны почта и пароль",
  "ja": "メールアドレスとパスワードが必要です", "zh": "需要邮箱和密码", "zh_TW": "需要電子郵件和密碼",
 },
 "accesso in corso…": {
  "en": "signing in…", "de": "Anmeldung läuft…", "fr": "connexion en cours…",
  "es": "accediendo…", "pt": "a entrar…", "nl": "bezig met aanmelden…",
  "ca": "accedint…", "da": "logger ind…", "hu": "belépés folyamatban…",
  "ro": "se autentifică…", "lv": "notiek pieteikšanās…", "ru": "выполняется вход…",
  "ja": "ログイン中…", "zh": "正在登录…", "zh_TW": "正在登入…",
 },
 "risposta incomprensibile dal server": {
  "en": "the server sent an answer I cannot read",
  "de": "unverständliche Antwort vom Server",
  "fr": "réponse incompréhensible du serveur",
  "es": "respuesta incomprensible del servidor",
  "pt": "resposta incompreensível do servidor",
  "nl": "onbegrijpelijk antwoord van de server",
  "ca": "resposta incomprensible del servidor",
  "da": "uforståeligt svar fra serveren",
  "hu": "értelmezhetetlen válasz a kiszolgálótól",
  "ro": "răspuns neinteligibil de la server",
  "lv": "nesaprotama servera atbilde",
  "ru": "непонятный ответ сервера",
  "ja": "サーバーの応答を解釈できません", "zh": "无法解析服务器的回复", "zh_TW": "無法解析伺服器的回覆",
 },
 "server non raggiungibile: %1": {
  "en": "server unreachable: %1", "de": "Server nicht erreichbar: %1",
  "fr": "serveur injoignable : %1", "es": "servidor inaccesible: %1",
  "pt": "servidor inacessível: %1", "nl": "server onbereikbaar: %1",
  "ca": "servidor inaccessible: %1", "da": "serveren kan ikke nås: %1",
  "hu": "a kiszolgáló nem érhető el: %1", "ro": "serverul nu răspunde: %1",
  "lv": "serveris nav sasniedzams: %1", "ru": "сервер недоступен: %1",
  "ja": "サーバーに接続できません: %1", "zh": "无法连接服务器：%1", "zh_TW": "無法連線伺服器：%1",
 },
 "accesso rifiutato": {
  "en": "sign-in refused", "de": "Anmeldung abgelehnt", "fr": "connexion refusée",
  "es": "acceso denegado", "pt": "acesso recusado", "nl": "aanmelding geweigerd",
  "ca": "accés denegat", "da": "login afvist", "hu": "belépés elutasítva",
  "ro": "autentificare respinsă", "lv": "pieteikšanās noraidīta", "ru": "во входе отказано",
  "ja": "ログインが拒否されました", "zh": "登录被拒绝", "zh_TW": "登入遭拒",
 },
 "titolare": {
  "en": "owner", "de": "Inhaber", "fr": "titulaire", "es": "titular", "pt": "titular",
  "nl": "eigenaar", "ca": "titular", "da": "indehaver", "hu": "tulajdonos",
  "ro": "titular", "lv": "īpašnieks", "ru": "владелец", "ja": "管理者",
  "zh": "台主", "zh_TW": "台主",
 },
 "operatore": {
  "en": "operator", "de": "Operator", "fr": "opérateur", "es": "operador",
  "pt": "operador", "nl": "operator", "ca": "operador", "da": "operatør",
  "hu": "kezelő", "ro": "operator", "lv": "operators", "ru": "оператор",
  "ja": "オペレーター", "zh": "操作员", "zh_TW": "操作員",
 },
 "ascoltatore": {
  "en": "listener", "de": "Zuhörer", "fr": "auditeur", "es": "oyente",
  "pt": "ouvinte", "nl": "luisteraar", "ca": "oient", "da": "lytter",
  "hu": "hallgató", "ro": "ascultător", "lv": "klausītājs", "ru": "слушатель",
  "ja": "リスナー", "zh": "收听者", "zh_TW": "收聽者",
 },
 " (solo ascolto)": {
  "en": " (listen only)", "de": " (nur Empfang)", "fr": " (écoute seule)",
  "es": " (solo escucha)", "pt": " (apenas escuta)", "nl": " (alleen luisteren)",
  "ca": " (només escolta)", "da": " (kun lytning)", "hu": " (csak hallgatás)",
  "ro": " (doar ascultare)", "lv": " (tikai klausīšanās)", "ru": " (только приём)",
  "ja": " (受信のみ)", "zh": "（仅收听）", "zh_TW": "（僅收聽）",
 },
 "credenziali scadute: rifaccio l'accesso": {
  "en": "credentials expired: signing in again",
  "de": "Zugangsdaten abgelaufen: melde mich erneut an",
  "fr": "identifiants expirés : je me reconnecte",
  "es": "credenciales caducadas: vuelvo a acceder",
  "pt": "credenciais expiradas: a entrar de novo",
  "nl": "inloggegevens verlopen: opnieuw aanmelden",
  "ca": "credencials caducades: torno a accedir",
  "da": "loginoplysninger udløbet: logger ind igen",
  "hu": "a hitelesítő adatok lejártak: újra belépek",
  "ro": "credențiale expirate: mă autentific din nou",
  "lv": "pieteikšanās dati beigušies: pieteikšos vēlreiz",
  "ru": "срок действия учётных данных истёк: вхожу заново",
  "ja": "認証情報の期限切れ: 再ログインします",
  "zh": "凭据已过期：正在重新登录", "zh_TW": "憑證已過期：正在重新登入",
 },
 "credenziali da rinnovare: rifaccio l'accesso": {
  "en": "credentials need renewing: signing in again",
  "de": "Zugangsdaten müssen erneuert werden: melde mich erneut an",
  "fr": "identifiants à renouveler : je me reconnecte",
  "es": "hay que renovar las credenciales: vuelvo a acceder",
  "pt": "credenciais a renovar: a entrar de novo",
  "nl": "inloggegevens moeten vernieuwd: opnieuw aanmelden",
  "ca": "cal renovar les credencials: torno a accedir",
  "da": "loginoplysninger skal fornys: logger ind igen",
  "hu": "a hitelesítő adatokat meg kell újítani: újra belépek",
  "ro": "credențialele trebuie reînnoite: mă autentific din nou",
  "lv": "jāatjauno pieteikšanās dati: pieteikšos vēlreiz",
  "ru": "нужно обновить учётные данные: вхожу заново",
  "ja": "認証情報の更新が必要です: 再ログインします",
  "zh": "凭据需要更新：正在重新登录", "zh_TW": "憑證需要更新：正在重新登入",
 },
 "manca l'accesso: premi Accedi, poi Avvia": {
  "en": "not signed in: press Sign in, then Start",
  "de": "nicht angemeldet: erst Anmelden, dann Start",
  "fr": "non connecté : appuyez sur Se connecter, puis Démarrer",
  "es": "sin acceso: pulsa Acceder y luego Iniciar",
  "pt": "sem acesso: carregue em Entrar e depois Iniciar",
  "nl": "niet aangemeld: druk op Aanmelden, dan Starten",
  "ca": "sense accés: prem Accedeix i després Inicia",
  "da": "ikke logget ind: tryk Log ind og derefter Start",
  "hu": "nincs belépve: nyomja meg a Belépés, majd az Indítás gombot",
  "ro": "neautentificat: apasă Autentificare, apoi Pornește",
  "lv": "nav pieteicies: nospiediet Pieteikties, tad Sākt",
  "ru": "вход не выполнен: нажмите Войти, затем Пуск",
  "ja": "未ログインです: ログイン してから 開始 を押してください",
  "zh": "尚未登录：请先点“登录”，再点“启动”",
  "zh_TW": "尚未登入：請先點「登入」，再點「啟動」",
 },
 "nessuna porta seriale": {
  "en": "no serial port", "de": "keine serielle Schnittstelle", "fr": "aucun port série",
  "es": "no hay puerto serie", "pt": "sem porta série", "nl": "geen seriële poort",
  "ca": "cap port sèrie", "da": "ingen seriel port", "hu": "nincs soros port",
  "ro": "niciun port serial", "lv": "nav seriālā porta", "ru": "нет последовательного порта",
  "ja": "シリアルポートがありません", "zh": "没有串口", "zh_TW": "沒有序列埠",
 },
 "indirizzo CI-V non valido": {
  "en": "invalid CI-V address", "de": "ungültige CI-V-Adresse",
  "fr": "adresse CI-V non valide", "es": "dirección CI-V no válida",
  "pt": "endereço CI-V inválido", "nl": "ongeldig CI-V-adres",
  "ca": "adreça CI-V no vàlida", "da": "ugyldig CI-V-adresse",
  "hu": "érvénytelen CI-V cím", "ro": "adresă CI-V nevalidă",
  "lv": "nederīga CI-V adrese", "ru": "неверный адрес CI-V",
  "ja": "CI-V アドレスが不正です", "zh": "CI-V 地址无效", "zh_TW": "CI-V 位址無效",
 },
 "manca l'indirizzo del programma che tiene la radio": {
  "en": "missing the address of the program holding the radio",
  "de": "Adresse des Programms fehlt, das das Funkgerät hält",
  "fr": "adresse manquante du programme qui détient la radio",
  "es": "falta la dirección del programa que tiene la radio",
  "pt": "falta o endereço do programa que detém o rádio",
  "nl": "adres ontbreekt van het programma dat de set bezet",
  "ca": "falta l'adreça del programa que té la ràdio",
  "da": "adressen på programmet der har radioen mangler",
  "hu": "hiányzik a rádiót birtokló program címe",
  "ro": "lipsește adresa programului care deține radioul",
  "lv": "trūkst programmas adreses, kas tur radio",
  "ru": "не указан адрес программы, которая держит трансивер",
  "ja": "無線機を保持しているプログラムのアドレスが未設定です",
  "zh": "缺少占用电台的程序地址", "zh_TW": "缺少占用電台的程式位址",
 },
 "%1 non risponde: %2": {
  "en": "%1 is not answering: %2", "de": "%1 antwortet nicht: %2",
  "fr": "%1 ne répond pas : %2", "es": "%1 no responde: %2",
  "pt": "%1 não responde: %2", "nl": "%1 antwoordt niet: %2",
  "ca": "%1 no respon: %2", "da": "%1 svarer ikke: %2",
  "hu": "%1 nem válaszol: %2", "ro": "%1 nu răspunde: %2",
  "lv": "%1 neatbild: %2", "ru": "%1 не отвечает: %2",
  "ja": "%1 が応答しません: %2", "zh": "%1 无响应：%2", "zh_TW": "%1 無回應：%2",
 },
 "%1 non si apre: %2": {
  "en": "%1 will not open: %2", "de": "%1 lässt sich nicht öffnen: %2",
  "fr": "%1 ne s'ouvre pas : %2", "es": "%1 no se abre: %2",
  "pt": "%1 não abre: %2", "nl": "%1 gaat niet open: %2",
  "ca": "%1 no s'obre: %2", "da": "%1 kan ikke åbnes: %2",
  "hu": "%1 nem nyitható meg: %2", "ro": "%1 nu se deschide: %2",
  "lv": "%1 neatveras: %2", "ru": "%1 не открывается: %2",
  "ja": "%1 を開けません: %2", "zh": "无法打开 %1：%2", "zh_TW": "無法開啟 %1：%2",
 },
 "il telefono è entrato nella stanza": {
  "en": "the phone has joined the room", "de": "Das Telefon ist dem Raum beigetreten",
  "fr": "le téléphone a rejoint la salle", "es": "el teléfono ha entrado en la sala",
  "pt": "o telemóvel entrou na sala", "nl": "de telefoon is de ruimte binnengekomen",
  "ca": "el telèfon ha entrat a la sala", "da": "telefonen er kommet ind i rummet",
  "hu": "a telefon belépett a szobába", "ro": "telefonul a intrat în cameră",
  "lv": "telefons ir pievienojies telpai", "ru": "телефон вошёл в комнату",
  "ja": "スマートフォンが部屋に入りました", "zh": "手机已加入房间", "zh_TW": "手機已加入房間",
 },
 "registrato sul relay come %1 (%2)": {
  "en": "registered on the relay as %1 (%2)",
  "de": "am Relay angemeldet als %1 (%2)",
  "fr": "enregistré sur le relais en tant que %1 (%2)",
  "es": "registrado en el relé como %1 (%2)",
  "pt": "registado no relé como %1 (%2)",
  "nl": "geregistreerd op de relay als %1 (%2)",
  "ca": "registrat al relé com a %1 (%2)",
  "da": "registreret på relæet som %1 (%2)",
  "hu": "regisztrálva a relén mint %1 (%2)",
  "ro": "înregistrat pe releu ca %1 (%2)",
  "lv": "reģistrēts relejā kā %1 (%2)",
  "ru": "зарегистрирован на ретрансляторе как %1 (%2)",
  "ja": "リレーに %1 (%2) として登録しました",
  "zh": "已在中继上注册为 %1（%2）", "zh_TW": "已在中繼上註冊為 %1（%2）",
 },
 "il relay ha rifiutato il collegamento: %1": {
  "en": "the relay refused the connection: %1",
  "de": "Das Relay hat die Verbindung abgelehnt: %1",
  "fr": "le relais a refusé la connexion : %1",
  "es": "el relé ha rechazado la conexión: %1",
  "pt": "o relé recusou a ligação: %1",
  "nl": "de relay heeft de verbinding geweigerd: %1",
  "ca": "el relé ha rebutjat la connexió: %1",
  "da": "relæet afviste forbindelsen: %1",
  "hu": "a relé elutasította a kapcsolatot: %1",
  "ro": "releul a refuzat conexiunea: %1",
  "lv": "relejs noraidīja savienojumu: %1",
  "ru": "ретранслятор отклонил подключение: %1",
  "ja": "リレーが接続を拒否しました: %1",
  "zh": "中继拒绝了连接：%1", "zh_TW": "中繼拒絕了連線：%1",
 },
 "registrato, ma nella stazione non c'è nessun altro: il telefono non è ancora entrato": {
  "en": "registered, but nobody else is in the station: the phone has not joined yet",
  "de": "angemeldet, aber sonst ist niemand in der Station: das Telefon ist noch nicht da",
  "fr": "enregistré, mais personne d'autre dans la station : le téléphone n'est pas encore entré",
  "es": "registrado, pero no hay nadie más en la estación: el teléfono aún no ha entrado",
  "pt": "registado, mas não há mais ninguém na estação: o telemóvel ainda não entrou",
  "nl": "geregistreerd, maar er is niemand anders in het station: de telefoon is er nog niet",
  "ca": "registrat, però no hi ha ningú més a l'estació: el telèfon encara no hi ha entrat",
  "da": "registreret, men der er ingen andre i stationen: telefonen er ikke kommet ind endnu",
  "hu": "regisztrálva, de rajtad kívül nincs senki az állomáson: a telefon még nem lépett be",
  "ro": "înregistrat, dar nu mai e nimeni în stație: telefonul încă nu a intrat",
  "lv": "reģistrēts, bet stacijā nav neviena cita: telefons vēl nav pievienojies",
  "ru": "зарегистрирован, но на станции больше никого нет: телефон ещё не вошёл",
  "ja": "登録済みですが、局には他に誰もいません: スマートフォンがまだ入っていません",
  "zh": "已注册，但电台里没有其他人：手机尚未加入",
  "zh_TW": "已註冊，但電台裡沒有其他人：手機尚未加入",
 },
 "trasmissione dal telefono in corso": {
  "en": "transmitting from the phone", "de": "Sendung vom Telefon läuft",
  "fr": "émission depuis le téléphone en cours", "es": "transmitiendo desde el teléfono",
  "pt": "a transmitir a partir do telemóvel", "nl": "zenden vanaf de telefoon",
  "ca": "transmetent des del telèfon", "da": "sender fra telefonen",
  "hu": "adás a telefonról folyamatban", "ro": "se transmite de pe telefon",
  "lv": "notiek pārraide no telefona", "ru": "идёт передача с телефона",
  "ja": "スマートフォンから送信中", "zh": "正在从手机发射", "zh_TW": "正在從手機發射",
 },
 "trasmissione finita": {
  "en": "transmission ended", "de": "Sendung beendet", "fr": "émission terminée",
  "es": "transmisión finalizada", "pt": "transmissão terminada", "nl": "uitzending beëindigd",
  "ca": "transmissió finalitzada", "da": "udsendelse afsluttet", "hu": "az adás véget ért",
  "ro": "transmisie încheiată", "lv": "pārraide beigusies", "ru": "передача окончена",
  "ja": "送信終了", "zh": "发射结束", "zh_TW": "發射結束",
 },
 "nessun ingresso audio": {
  "en": "no audio input", "de": "kein Audioeingang", "fr": "aucune entrée audio",
  "es": "sin entrada de audio", "pt": "sem entrada de áudio", "nl": "geen audio-ingang",
  "ca": "cap entrada d'àudio", "da": "ingen lydindgang", "hu": "nincs hangbemenet",
  "ro": "nicio intrare audio", "lv": "nav audio ievades", "ru": "нет звукового входа",
  "ja": "音声入力がありません", "zh": "没有音频输入", "zh_TW": "沒有音訊輸入",
 },
 "impossibile aprire l'ingresso audio": {
  "en": "cannot open the audio input", "de": "Audioeingang lässt sich nicht öffnen",
  "fr": "impossible d'ouvrir l'entrée audio", "es": "no se puede abrir la entrada de audio",
  "pt": "não é possível abrir a entrada de áudio", "nl": "kan de audio-ingang niet openen",
  "ca": "no es pot obrir l'entrada d'àudio", "da": "kan ikke åbne lydindgangen",
  "hu": "a hangbemenet nem nyitható meg", "ro": "nu se poate deschide intrarea audio",
  "lv": "nevar atvērt audio ievadi", "ru": "не удаётся открыть звуковой вход",
  "ja": "音声入力を開けません", "zh": "无法打开音频输入", "zh_TW": "無法開啟音訊輸入",
 },
 "%1 non supporta 48 kHz mono 16 bit": {
  "en": "%1 does not support 48 kHz mono 16 bit",
  "de": "%1 unterstützt kein 48 kHz Mono 16 Bit",
  "fr": "%1 ne prend pas en charge 48 kHz mono 16 bits",
  "es": "%1 no admite 48 kHz mono 16 bits",
  "pt": "%1 não suporta 48 kHz mono 16 bits",
  "nl": "%1 ondersteunt geen 48 kHz mono 16 bit",
  "ca": "%1 no admet 48 kHz mono 16 bits",
  "da": "%1 understøtter ikke 48 kHz mono 16 bit",
  "hu": "a(z) %1 nem támogatja a 48 kHz mono 16 bitet",
  "ro": "%1 nu acceptă 48 kHz mono 16 biți",
  "lv": "%1 neatbalsta 48 kHz mono 16 bitu",
  "ru": "%1 не поддерживает 48 кГц моно 16 бит",
  "ja": "%1 は 48 kHz モノラル 16 ビットに対応していません",
  "zh": "%1 不支持 48 kHz 单声道 16 位", "zh_TW": "%1 不支援 48 kHz 單聲道 16 位元",
 },
 "manca l'host di destinazione": {
  "en": "the destination host is missing", "de": "Der Ziel-Host fehlt",
  "fr": "l'hôte de destination manque", "es": "falta el host de destino",
  "pt": "falta o servidor de destino", "nl": "de doelhost ontbreekt",
  "ca": "falta l'amfitrió de destinació", "da": "målværten mangler",
  "hu": "hiányzik a cél kiszolgáló", "ro": "lipsește gazda de destinație",
  "lv": "trūkst mērķa resursdatora", "ru": "не указан адрес назначения",
  "ja": "接続先ホストが未設定です", "zh": "缺少目标主机", "zh_TW": "缺少目標主機",
 },
 "nome non risolto: %1": {
  "en": "name not resolved: %1", "de": "Name nicht aufgelöst: %1",
  "fr": "nom non résolu : %1", "es": "nombre no resuelto: %1",
  "pt": "nome não resolvido: %1", "nl": "naam niet herleid: %1",
  "ca": "nom no resolt: %1", "da": "navnet kunne ikke slås op: %1",
  "hu": "a név nem oldható fel: %1", "ro": "nume nerezolvat: %1",
  "lv": "vārds nav atrisināts: %1", "ru": "имя не разрешено: %1",
  "ja": "名前を解決できません: %1", "zh": "无法解析名称：%1", "zh_TW": "無法解析名稱：%1",
 },
 "accedi prima: il relay non accetta collegamenti senza credenziali": {
  "en": "sign in first: the relay does not accept connections without credentials",
  "de": "erst anmelden: das Relay nimmt keine Verbindungen ohne Zugangsdaten an",
  "fr": "connectez-vous d'abord : le relais n'accepte pas de connexion sans identifiants",
  "es": "accede primero: el relé no acepta conexiones sin credenciales",
  "pt": "entre primeiro: o relé não aceita ligações sem credenciais",
  "nl": "meld je eerst aan: de relay accepteert geen verbindingen zonder inloggegevens",
  "ca": "accedeix primer: el relé no accepta connexions sense credencials",
  "da": "log ind først: relæet accepterer ikke forbindelser uden loginoplysninger",
  "hu": "előbb lépjen be: a relé nem fogad kapcsolatot hitelesítő adatok nélkül",
  "ro": "autentifică-te mai întâi: releul nu acceptă conexiuni fără credențiale",
  "lv": "vispirms piesakieties: relejs nepieņem savienojumus bez pieteikšanās datiem",
  "ru": "сначала войдите: ретранслятор не принимает подключения без учётных данных",
  "ja": "先にログインしてください: リレーは認証情報なしの接続を受け付けません",
  "zh": "请先登录：中继不接受没有凭据的连接",
  "zh_TW": "請先登入：中繼不接受沒有憑證的連線",
 },
 "porta %1 non disponibile": {
  "en": "port %1 not available", "de": "Port %1 nicht verfügbar",
  "fr": "port %1 non disponible", "es": "puerto %1 no disponible",
  "pt": "porta %1 indisponível", "nl": "poort %1 niet beschikbaar",
  "ca": "port %1 no disponible", "da": "port %1 er ikke tilgængelig",
  "hu": "a(z) %1 port nem érhető el", "ro": "portul %1 nu este disponibil",
  "lv": "ports %1 nav pieejams", "ru": "порт %1 недоступен",
  "ja": "ポート %1 は使用できません", "zh": "端口 %1 不可用", "zh_TW": "連接埠 %1 無法使用",
 },
 "porta TCP %1 occupata (rigctld è già in esecuzione?)": {
  "en": "TCP port %1 is busy (is rigctld already running?)",
  "de": "TCP-Port %1 belegt (läuft rigctld bereits?)",
  "fr": "port TCP %1 occupé (rigctld est-il déjà lancé ?)",
  "es": "puerto TCP %1 ocupado (¿ya se está ejecutando rigctld?)",
  "pt": "porta TCP %1 ocupada (o rigctld já está em execução?)",
  "nl": "TCP-poort %1 bezet (draait rigctld al?)",
  "ca": "port TCP %1 ocupat (ja s'està executant rigctld?)",
  "da": "TCP-port %1 optaget (kører rigctld allerede?)",
  "hu": "a(z) %1 TCP port foglalt (fut már a rigctld?)",
  "ro": "portul TCP %1 este ocupat (rulează deja rigctld?)",
  "lv": "TCP ports %1 ir aizņemts (vai rigctld jau darbojas?)",
  "ru": "TCP-порт %1 занят (rigctld уже запущен?)",
  "ja": "TCP ポート %1 は使用中です (rigctld が既に動作中?)",
  "zh": "TCP 端口 %1 被占用（rigctld 是否已在运行？）",
  "zh_TW": "TCP 連接埠 %1 被占用（rigctld 是否已在執行？）",
 },
 "la porta TCP %1 e' la stessa a cui ti stai collegando: cambiane una": {
  "en": "TCP port %1 is the same one you are connecting to: change one of them",
  "de": "TCP-Port %1 ist derselbe, zu dem du dich verbindest: ändere einen davon",
  "fr": "le port TCP %1 est celui auquel vous vous connectez : changez-en un",
  "es": "el puerto TCP %1 es el mismo al que te conectas: cambia uno de los dos",
  "pt": "a porta TCP %1 é a mesma a que te estás a ligar: muda uma delas",
  "nl": "TCP-poort %1 is dezelfde waarmee je verbindt: wijzig er één",
  "ca": "el port TCP %1 és el mateix al qual et connectes: canvia'n un",
  "da": "TCP-port %1 er den samme, du forbinder til: skift en af dem",
  "hu": "a(z) %1 TCP port ugyanaz, amelyhez csatlakozik: változtassa meg az egyiket",
  "ro": "portul TCP %1 este același la care te conectezi: schimbă-l pe unul",
  "lv": "TCP ports %1 ir tas pats, kuram pieslēdzaties: nomainiet vienu no tiem",
  "ru": "TCP-порт %1 совпадает с тем, к которому вы подключаетесь: измените один из них",
  "ja": "TCP ポート %1 は接続先と同じです: どちらかを変更してください",
  "zh": "TCP 端口 %1 与你要连接的端口相同：请改一个",
  "zh_TW": "TCP 連接埠 %1 與你要連線的相同：請改一個",
 },
 "rig: %1 MHz  %2   (TCP %3, e sul canale audio)": {
  "en": "rig: %1 MHz  %2   (TCP %3, and over the audio channel)",
  "de": "Funkgerät: %1 MHz  %2   (TCP %3, und über den Audiokanal)",
  "fr": "radio : %1 MHz  %2   (TCP %3, et sur le canal audio)",
  "es": "radio: %1 MHz  %2   (TCP %3, y por el canal de audio)",
  "pt": "rádio: %1 MHz  %2   (TCP %3, e pelo canal de áudio)",
  "nl": "set: %1 MHz  %2   (TCP %3, en via het audiokanaal)",
  "ca": "ràdio: %1 MHz  %2   (TCP %3, i pel canal d'àudio)",
  "da": "radio: %1 MHz  %2   (TCP %3, og via lydkanalen)",
  "hu": "rádió: %1 MHz  %2   (TCP %3, és a hangcsatornán)",
  "ro": "radio: %1 MHz  %2   (TCP %3, și pe canalul audio)",
  "lv": "radio: %1 MHz  %2   (TCP %3, un pa audio kanālu)",
  "ru": "трансивер: %1 МГц  %2   (TCP %3, и по звуковому каналу)",
  "ja": "無線機: %1 MHz  %2   (TCP %3、音声チャンネル経由)",
  "zh": "电台：%1 MHz  %2   （TCP %3，并通过音频通道）",
  "zh_TW": "電台：%1 MHz  %2   （TCP %3，並透過音訊通道）",
 },
 "rig non risponde sulla seriale": {
  "en": "the rig is not answering on the serial port",
  "de": "Funkgerät antwortet nicht auf der seriellen Schnittstelle",
  "fr": "la radio ne répond pas sur le port série",
  "es": "la radio no responde por el puerto serie",
  "pt": "o rádio não responde na porta série",
  "nl": "de set antwoordt niet op de seriële poort",
  "ca": "la ràdio no respon pel port sèrie",
  "da": "radioen svarer ikke på den serielle port",
  "hu": "a rádió nem válaszol a soros porton",
  "ro": "radioul nu răspunde pe portul serial",
  "lv": "radio neatbild uz seriālā porta",
  "ru": "трансивер не отвечает на последовательном порту",
  "ja": "無線機がシリアルポートで応答しません",
  "zh": "电台在串口上无响应", "zh_TW": "電台在序列埠上無回應",
 },
 "telefono connesso da %1:%2": {
  "en": "phone connected from %1:%2", "de": "Telefon verbunden von %1:%2",
  "fr": "téléphone connecté depuis %1:%2", "es": "teléfono conectado desde %1:%2",
  "pt": "telemóvel ligado a partir de %1:%2", "nl": "telefoon verbonden vanaf %1:%2",
  "ca": "telèfon connectat des de %1:%2", "da": "telefon forbundet fra %1:%2",
  "hu": "a telefon csatlakozott innen: %1:%2", "ro": "telefon conectat de la %1:%2",
  "lv": "telefons savienots no %1:%2", "ru": "телефон подключён с %1:%2",
  "ja": "スマートフォンが %1:%2 から接続しました",
  "zh": "手机已从 %1:%2 连接", "zh_TW": "手機已從 %1:%2 連線",
 },
 "telefono non più raggiungibile — attendo che richiami": {
  "en": "phone no longer reachable — waiting for it to call back",
  "de": "Telefon nicht mehr erreichbar — warte auf Rückruf",
  "fr": "téléphone injoignable — j'attends qu'il rappelle",
  "es": "el teléfono ya no responde — espero a que vuelva a llamar",
  "pt": "telemóvel inacessível — aguardo que volte a ligar",
  "nl": "telefoon niet meer bereikbaar — ik wacht tot hij terugbelt",
  "ca": "el telèfon ja no és accessible — espero que torni a trucar",
  "da": "telefonen kan ikke længere nås — venter på at den ringer igen",
  "hu": "a telefon már nem érhető el — várom, hogy visszahívjon",
  "ro": "telefonul nu mai este accesibil — aștept să sune din nou",
  "lv": "telefons vairs nav sasniedzams — gaidu, kad tas atzvanīs",
  "ru": "телефон больше недоступен — жду, когда он выйдет на связь",
  "ja": "スマートフォンに接続できません — 再接続を待っています",
  "zh": "手机已失联 — 等待它重新连接",
  "zh_TW": "手機已失聯 — 等待它重新連線",
 },
 "in ascolto sulla porta %1 — attendo il telefono": {
  "en": "listening on port %1 — waiting for the phone",
  "de": "höre auf Port %1 — warte auf das Telefon",
  "fr": "à l'écoute sur le port %1 — j'attends le téléphone",
  "es": "escuchando en el puerto %1 — espero al teléfono",
  "pt": "à escuta na porta %1 — aguardo o telemóvel",
  "nl": "luistert op poort %1 — wacht op de telefoon",
  "ca": "escoltant al port %1 — espero el telèfon",
  "da": "lytter på port %1 — venter på telefonen",
  "hu": "figyelés a(z) %1 porton — várom a telefont",
  "ro": "ascult pe portul %1 — aștept telefonul",
  "lv": "klausos portā %1 — gaidu telefonu",
  "ru": "слушаю порт %1 — жду телефон",
  "ja": "ポート %1 で待ち受け中 — スマートフォンを待っています",
  "zh": "正在端口 %1 监听 — 等待手机", "zh_TW": "正在連接埠 %1 監聽 — 等待手機",
 },
 "invio a %1:%2": {
  "en": "sending to %1:%2", "de": "sende an %1:%2", "fr": "envoi vers %1:%2",
  "es": "enviando a %1:%2", "pt": "a enviar para %1:%2", "nl": "verzenden naar %1:%2",
  "ca": "enviant a %1:%2", "da": "sender til %1:%2", "hu": "küldés ide: %1:%2",
  "ro": "trimit către %1:%2", "lv": "sūtu uz %1:%2", "ru": "отправка на %1:%2",
  "ja": "%1:%2 へ送信中", "zh": "正在发送到 %1:%2", "zh_TW": "正在傳送到 %1:%2",
 },
 "Opus non si avvia (%1): resto sul PCM": {
  "en": "Opus will not start (%1): staying on PCM",
  "de": "Opus startet nicht (%1): bleibe bei PCM",
  "fr": "Opus ne démarre pas (%1) : je reste en PCM",
  "es": "Opus no arranca (%1): sigo en PCM",
  "pt": "O Opus não arranca (%1): fico em PCM",
  "nl": "Opus start niet (%1): ik blijf op PCM",
  "ca": "L'Opus no arrenca (%1): em quedo en PCM",
  "da": "Opus starter ikke (%1): bliver på PCM",
  "hu": "Az Opus nem indul (%1): marad a PCM",
  "ro": "Opus nu pornește (%1): rămân pe PCM",
  "lv": "Opus nesāk darboties (%1): palieku uz PCM",
  "ru": "Opus не запускается (%1): остаюсь на PCM",
  "ja": "Opus を開始できません (%1): PCM のままにします",
  "zh": "Opus 无法启动（%1）：保持 PCM", "zh_TW": "Opus 無法啟動（%1）：保持 PCM",
 },
 "profilo riportato a PCM 48 kHz: i profili compressi richiedono un telefono aggiornato": {
  "en": "profile reset to PCM 48 kHz: compressed profiles need an updated phone",
  "de": "Profil auf PCM 48 kHz zurückgesetzt: komprimierte Profile brauchen ein aktuelles Telefon",
  "fr": "profil ramené à PCM 48 kHz : les profils compressés exigent un téléphone à jour",
  "es": "perfil devuelto a PCM 48 kHz: los perfiles comprimidos necesitan un teléfono actualizado",
  "pt": "perfil reposto em PCM 48 kHz: os perfis comprimidos exigem um telemóvel atualizado",
  "nl": "profiel terug op PCM 48 kHz: gecomprimeerde profielen vereisen een bijgewerkte telefoon",
  "ca": "perfil retornat a PCM 48 kHz: els perfils comprimits necessiten un telèfon actualitzat",
  "da": "profil sat tilbage til PCM 48 kHz: komprimerede profiler kræver en opdateret telefon",
  "hu": "a profil visszaállt PCM 48 kHz-re: a tömörített profilokhoz frissített telefon kell",
  "ro": "profil readus la PCM 48 kHz: profilurile comprimate necesită un telefon actualizat",
  "lv": "profils atgriezts uz PCM 48 kHz: saspiestajiem profiliem vajadzīgs atjaunināts telefons",
  "ru": "профиль возвращён на PCM 48 кГц: сжатые профили требуют обновлённого телефона",
  "ja": "プロファイルを PCM 48 kHz に戻しました: 圧縮プロファイルには更新されたスマートフォンが必要です",
  "zh": "配置已回到 PCM 48 kHz：压缩配置需要更新过的手机",
  "zh_TW": "設定檔已回到 PCM 48 kHz：壓縮設定檔需要更新過的手機",
 },
 "campionamento a %1 kHz: se il telefono lo sente accelerato, torna a 48": {
  "en": "sampling at %1 kHz: if the phone plays it sped up, go back to 48",
  "de": "Abtastung mit %1 kHz: klingt es am Telefon zu schnell, zurück auf 48",
  "fr": "échantillonnage à %1 kHz : si le téléphone l'entend accéléré, revenez à 48",
  "es": "muestreo a %1 kHz: si el teléfono lo oye acelerado, vuelve a 48",
  "pt": "amostragem a %1 kHz: se o telemóvel o ouvir acelerado, volte a 48",
  "nl": "bemonstering op %1 kHz: klinkt het op de telefoon versneld, ga terug naar 48",
  "ca": "mostreig a %1 kHz: si el telèfon el sent accelerat, torna a 48",
  "da": "sampling ved %1 kHz: lyder det hurtigt på telefonen, gå tilbage til 48",
  "hu": "mintavételezés %1 kHz-en: ha a telefonon felgyorsítva szól, térjen vissza 48-ra",
  "ro": "eșantionare la %1 kHz: dacă telefonul îl aude accelerat, revino la 48",
  "lv": "iztveršana ar %1 kHz: ja telefonā skan paātrināti, atgriezieties uz 48",
  "ru": "дискретизация %1 кГц: если на телефоне звук ускорен, вернитесь на 48",
  "ja": "サンプリング %1 kHz: スマートフォンで速く聞こえる場合は 48 に戻してください",
  "zh": "采样率 %1 kHz：如果手机听起来变快，请改回 48",
  "zh_TW": "取樣率 %1 kHz：如果手機聽起來變快，請改回 48",
 },
 "il telefono legge i pacchetti raggruppati: banda ridotta": {
  "en": "the phone reads grouped packets: bandwidth reduced",
  "de": "Das Telefon liest gebündelte Pakete: Bandbreite reduziert",
  "fr": "le téléphone lit les paquets groupés : bande passante réduite",
  "es": "el teléfono lee los paquetes agrupados: ancho de banda reducido",
  "pt": "o telemóvel lê os pacotes agrupados: largura de banda reduzida",
  "nl": "de telefoon leest gegroepeerde pakketten: minder bandbreedte",
  "ca": "el telèfon llegeix els paquets agrupats: amplada de banda reduïda",
  "da": "telefonen læser grupperede pakker: reduceret båndbredde",
  "hu": "a telefon olvassa a csoportosított csomagokat: csökkentett sávszélesség",
  "ro": "telefonul citește pachetele grupate: lățime de bandă redusă",
  "lv": "telefons lasa grupētās paketes: samazināts joslas platums",
  "ru": "телефон читает сгруппированные пакеты: полоса снижена",
  "ja": "スマートフォンがまとめたパケットを読めます: 帯域を削減しました",
  "zh": "手机可读取合并的数据包：带宽已降低",
  "zh_TW": "手機可讀取合併的封包：頻寬已降低",
 },
 "il telefono vuole un frame per pacchetto": {
  "en": "the phone wants one frame per packet",
  "de": "Das Telefon möchte einen Frame pro Paket",
  "fr": "le téléphone veut une trame par paquet",
  "es": "el teléfono quiere una trama por paquete",
  "pt": "o telemóvel quer uma trama por pacote",
  "nl": "de telefoon wil één frame per pakket",
  "ca": "el telèfon vol una trama per paquet",
  "da": "telefonen vil have én frame pr. pakke",
  "hu": "a telefon csomagonként egy keretet kér",
  "ro": "telefonul vrea un cadru per pachet",
  "lv": "telefons vēlas vienu kadru uz paketi",
  "ru": "телефон хочет по одному кадру в пакете",
  "ja": "スマートフォンは 1 パケット 1 フレームを要求しています",
  "zh": "手机要求每个包一帧", "zh_TW": "手機要求每個封包一幀",
 },
 "profilo su richiesta del telefono: %1": {
  "en": "profile requested by the phone: %1",
  "de": "Profil auf Wunsch des Telefons: %1",
  "fr": "profil demandé par le téléphone : %1",
  "es": "perfil solicitado por el teléfono: %1",
  "pt": "perfil pedido pelo telemóvel: %1",
  "nl": "profiel op verzoek van de telefoon: %1",
  "ca": "perfil sol·licitat pel telèfon: %1",
  "da": "profil ønsket af telefonen: %1",
  "hu": "a telefon által kért profil: %1",
  "ro": "profil cerut de telefon: %1",
  "lv": "telefona pieprasītais profils: %1",
  "ru": "профиль по запросу телефона: %1",
  "ja": "スマートフォンの要求によるプロファイル: %1",
  "zh": "手机请求的配置：%1", "zh_TW": "手機要求的設定檔：%1",
 },
 "token scaduto: lo rinnovo": {
  "en": "token expired: renewing it", "de": "Token abgelaufen: erneuere es",
  "fr": "jeton expiré : je le renouvelle", "es": "token caducado: lo renuevo",
  "pt": "token expirado: a renovar", "nl": "token verlopen: ik vernieuw het",
  "ca": "testimoni caducat: el renovo", "da": "token udløbet: fornyer det",
  "hu": "a token lejárt: megújítom", "ro": "token expirat: îl reînnoiesc",
  "lv": "marķieris beidzies: atjaunoju to", "ru": "токен истёк: обновляю",
  "ja": "トークンの期限切れ: 更新します", "zh": "令牌已过期：正在续期", "zh_TW": "權杖已過期：正在續期",
 },
}
